version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

  php:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./project:/var/www/html
    ports:
      - '8080:80'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '8181:80'

volumes:
  db_data:
